# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Experimental Books"
description: "Exploring the future of manuscript generation through AI-assisted writing"
baseurl: "/experimental-books" # the subpath of your site
url: "https://azuremis.github.io" # your GitHub Pages URL

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Collections
collections:
  books:
    output: true
    permalink: /books/:path/

# Navigation
header_pages:
  - books.md

# Theme-specific settings
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/azuremis/experimental-books"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 Experimental Books. Distributed under an MIT license."

# Social links (optional)
github_username: azuremis
twitter_username: azuremis

# Exclude development-specific files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
